get_data:
  source_file: remote\deliveryDatasetChallenge.json
  outpath: data

prepare_data:
  datafile: data\train_data.csv
  seed: 40
  split: 0.25
  outpath: features

training:
  data_dir: features
  outpath: model
  penalty: l2
  alpha: 0.0001
  depth: 10
  min_samples_split: 4

evaluate:
  model_dir: model
  outpath: metrics


