stages:
  preprocessing:
    cmd: python src\get_data.py --datafile remote/deliveryDatasetChallenge.json --outpath
      data
    deps:
    - remote/deliveryDatasetChallenge.json
    outs:
    - data\train_data.csv
  prepare:
    cmd: python src\prepare_data.py
    deps:
    - data\train_data.csv
    - src\prepare_data.py
    params:
    - prepare_data.seed
    - prepare_data.split
    - prepare_data.datafile
    - prepare_data.outpath
    outs:
    - features\X_pca_resampled.pkl
    - features\X_pca_test.pkl
    - features\y_resampled.pkl
    - features\y_test.pkl
  train:
    cmd: python src\train_model.py
    deps:
    - src\train_model.py
    - features\X_pca_resampled.pkl
    - features\y_resampled.pkl
    params:
    - training.data_dir
    - training.outpath
    - training.depth
    - training.penalty
    - training.alpha
    - training.min_samples_split
    metrics_no_cache:
    - metrics/train_metric.json
    outs:
    - model\SGDCClassifier.pkl
  evaluate:
    cmd: python src\evaluate_model.py --model_dir model --data_dir features
    deps:
    - features\X_pca_test.pkl
    - features\y_test.pkl
    - model\SGDCClassifier.pkl
    - src\evaluate_model.py
    metrics_no_cache:
    - metrics\evaluate_metrics.json
